#!/bin/bash

# REMOTE_PATH_2 = /var/www/git
# REMOTE_DIR = gofetch.git

REMOTE_HTML_DIR="/var/www/html";
REMOTE_PROJ_HTML_DIR=$REMOTE_HTML_DIR/$LOCAL_DIR;

mkdir $REMOTE_PROJ_HTML_DIR;
cd $REMOTE_PROJ_HTML_DIR;
stagit $REMOTE_PATH_2/$REMOTE_DIR;

cd $REMOTE_HTML_DIR;
stagit-index $REMOTE_PATH_2/$REMOTE_DIR > index.html;

sed -i 's%href="style.css"%href="stagit-config/stagit-assets/style.css"%g' $REMOTE_HTML_DIR/index.html;
